- src/unittestScripts.ts
- src/unittestSuitParser.ts
- test/unittestSuitParserTest.ts
Fixes #8 #9 
I will note that i do not write typescript, so if my code is not sufficient please suggest a change.
> Fixes problems with test suites that print on import, also fixes problems with test suites that use setUpClass

- src/unittestScripts.ts
- test/test_samples/unittest_general/setup_tests/test_with_setup.py
- test/unittestGeneral.test.ts
> Fix test running with start directory

- src/configurationFactory.ts
- src/placeholderAwareWorkspaceConfiguration.ts
- src/pythonTestAdapter.ts
- src/vscodeWorkspaceConfiguration.ts
- test/placeholderAwareWorkspaceConfiguration.test.ts
- test/test_samples/samples-workspace.code-workspace
- test/test_samples/workspaces/python_extension_configured_with_placeholders/.vscode/settings.json
- test/vscodeWorkspaceConfiguration.test.ts
> Resolve placeholders in configuration

- src/pythonRunner.ts
- src/pythonTestAdapter.ts
- test/pythonTestAdapter.test.ts
- test/test_samples/pytest/test/generate_test.py
- test/test_samples/unittest/basic_tests/initialization_output_tests/test_with_initialization_output.py
> Sort test cases alphabetically

- requirements.txt
- src/pytest/pytestTestCollectionParser.ts
- test/pytestGeneral.test.ts
- test/pytestTestCollectionParser.test.ts
- test/test_samples/pytest/test/describe_test.py
> Support pytest-describe plugin

- src/configuration/configurationFactory.ts
- src/configuration/placeholderAwareWorkspaceConfiguration.ts
- test/helpers.ts
- test/index.ts
- test/placeholderAwareWorkspaceConfiguration.test.ts
> Add more placeholders for configuration

- .azure-pipelines.yml
- .travis.yml
- src/pytest/pytestJunitTestStatesParser.ts
- src/pytest/pytestTestRunner.ts
- src/pythonRunner.ts
- src/pythonTestAdapter.ts
- src/testRunner.ts
- src/unittest/unittestScripts.ts
- src/unittest/unittestSuitParser.ts
- src/unittest/unittestTestRunner.ts
- test/helpers.ts
- test/index.ts
- test/testCancellation.test.ts
- test/test_samples/pytest_test_cancellation/.vscode/settings.json
- test/test_samples/pytest_test_cancellation/test_sleep.py
- test/test_samples/samples-workspace.code-workspace
- test/test_samples/unittest_test_cancellation/.vscode/settings.json
- test/test_samples/unittest_test_cancellation/test_sleep.py
- test/unittestSuitParser.test.ts
> Add test cancellation 

- src/configuration/vscodeWorkspaceConfiguration.ts
- src/utilities.ts
- test/test_samples/pytest/.vscode/settings.json
- test/test_samples/pytest_test_cancellation/.vscode/settings.json
- test/test_samples/unittest/.vscode/settings.json
- test/test_samples/unittest_test_cancellation/.vscode/settings.json
- test/test_samples/workspaces/bad_env_file/.vscode/settings.json
- test/test_samples/workspaces/not_existent_env_file/.vscode/settings.json
- test/test_samples/workspaces/python_extension_configured_pytest/.vscode/settings.json
- test/test_samples/workspaces/python_extension_configured_unittest/.vscode/settings.json
- test/test_samples/workspaces/python_extension_configured_with_placeholders/.vscode/settings.json
- test/test_samples/workspaces/test_framework_overridden_and_default/.vscode/settings.json
> Fix renaming configuration settings

- src/pytest/pytestTestRunner.ts
- test/pytestArguments.test.ts
> Handle pytest positional arguments

- src/unittest/unittestSuitParser.ts
- test/unittestSuitParser.test.ts
> Add file property for unittest test methods

- .azure-pipelines.yml
- src/pytest/pytestTestRunner.ts
- src/pythonTestAdapter.ts
- test/pytestArguments.test.ts
- test/test_samples/pytest/test/inner_tests/add_test.py
- test/test_samples/pytest/test/other_tests/add_test.py
> Fix debug config, add pytest mark tests

- src/configuration/vscodeWorkspaceConfiguration.ts
- src/pytest/pytestTestRunner.ts
> Better error reporting on invalid arguments

- src/pytest/pytestTestRunner.ts
- test/test_samples/pytest/pytest.ini
> Force pytest to use xunit1 report

- src/configuration/placeholderAwareWorkspaceConfiguration.ts
- test/tests/placeholderAwareWorkspaceConfiguration.test.ts
- test/tests/pytestGeneral.test.ts
- test/utils/helpers.ts
> Fix cwd resolution

- README.md
> Add section on Test Explorer UI configuration

- package-lock.json
- package.json
- src/configuration/vscodeWorkspaceConfiguration.ts
- src/environmentVariablesLoader.ts
- src/pytest/pytestJunitTestStatesParser.ts
- src/pytest/pytestTestCollectionParser.ts
- src/pytest/pytestTestRunner.ts
- src/pythonTestAdapter.ts
- src/unittest/unittestSuitParser.ts
- src/unittest/unittestTestRunner.ts
- src/utilities/collections.ts
- src/utilities/fs.ts
- src/utilities/tests.ts
> Load debug configuration from launch.json

- .gitignore
- src/pytest/pytestTestRunner.ts
- test/test_samples/pytest/.vscode/settings.json
- test/tests/pytestArguments.test.ts
> Support custom junit path

- src/pythonTestAdapter.ts
- test/test_samples/pytest/.vscode/launch.json
> Debug console config

- package.json
> Add onStartupFinished activation event

- src/configuration/configurationFactory.ts
- src/configuration/pythonExtensionAwareWorkspaceConfiguration.ts
- src/configuration/vscodeWorkspaceConfiguration.ts
- src/pythonTestAdapter.ts
- test/test_samples/pytest/.vscode/settings.json
- test/tests/pythonTestAdapter.test.ts
> Use python auto detection

- src/configuration/placeholderAwareWorkspaceConfiguration.ts
- src/configuration/pythonExtensionAwareWorkspaceConfiguration.ts
- src/configuration/vscodeWorkspaceConfiguration.ts
- src/configuration/workspaceConfiguration.ts
- src/logging/defaultLogger.ts
- src/pytest/pytestTestRunner.ts
- src/pythonTestAdapter.ts
- src/unittest/unittestTestRunner.ts
- test/tests/environmentParsing.test.ts
- test/tests/placeholderAwareWorkspaceConfiguration.test.ts
- test/tests/pytestScript.test.ts
- test/tests/unittestGeneral.test.ts
- test/utils/helpers.ts
> Add auto-reload and auto-run for tests

- .vscodeignore
- src/configuration/pythonExtensionAwareWorkspaceConfiguration.ts
> Fallback if failed to auto-detect pythonPath, fix vscodeignore

- src/pytest/pytestTestRunner.ts
- test/test_samples/pytest/test/submodule/pytest.ini
- test/test_samples/pytest/test/submodule/test_simple.py
- test/tests/pytestArguments.test.ts
- test/tests/pytestGeneral.test.ts
- test/tests/pytestScript.test.ts
- test/utils/pytest.ts
> Always set rootdir to current working directory

- src/pytest/pytestJunitTestStatesParser.ts
- test/test_samples/pytest/test/inner_tests/add_test.py
- test/tests/pytestGeneral.test.ts
- test/tests/pytestScript.test.ts
> Show stderr in test output for pytest

- resources/python/vscode_python_test_adapter/pytest/discovery_output_plugin.py
- src/pytest/pytestTestCollectionParser.ts
- test/tests/pythonTestAdapter.test.ts
> Suite for parameterized

- .azure-pipelines.yml
- src/pytest/pytestJunitTestStatesParser.ts
- src/utilities/strings.ts
- test/tests/environmentParsing.test.ts
- tox.ini
For #232 
Screenshot from debugging for future references
> Hacky fix for pytest result parsing

- src/pytest/pytestJunitTestStatesParser.ts
- src/pytest/pytestTestRunner.ts
- src/utilities/strings.ts
- test/test_samples/pytest/pytest.ini
- test/tests/utilities.test.ts
> Fix pytest returning empty output

- .azure-pipelines.yml
- .github/workflows/ci.yml
- .vscode/launch.json
- package-lock.json
- package.json
- src/testplan/testplanTestRunner.ts
- test/tests/utilities.ts
- tox.ini
- pattern -> pattern in testplan runner (This was always a typo, but it resolved by prefix till a new commandline switch were added)
- update dependency versions
- update tox config
- remove 2.7 from and add 3.11 to pipelines
> change typo in commandline switch for testplan runner & version updates
